### ISSUE TITLE
DDMS+ Backup issue (Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded at java...)

### ISSUE THREAD

**Issue by Niteen12345** [terraframe/DDMS#16]
Automated backup of DDMS+ (through automated backup script or command line utility) is not working properly, it generates corrupt backup files. I tried to take backup with command line utility (script is written in backup and mirror.bat file), DDMS+ start generating backup files. After some time (approx. 1.25 hrs) unfortunately an error messages ' Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded at java........' appears on command line utility screen.
![Screenshot no-2](https://user-images.githubusercontent.com/108218237/175809912-4a150eeb-bcd9-46a2-8e9a-87555a993267.png)

After investigating the error, I found that this error comes when the JVM ( java virtual machine ) is spending more time in garbage collection than usual and no more memory available by the garbage collector so exceeding the maximum Heap memory of the JVM application.

The solution of this error is to increase the maximum Heap memory (-Xmx ). I checked the java code in DDMS (manager.ps1) and see that the default value of Heap memory is set to be ( -Xms128m  -Xmx1028m ). I changed this value as ( -Xms1024m  -Xmx2048m ) and try to take the backup, this time it works fine and able to generate the backup without any error. Automated backup (from Task scheduler ) is also working fine after this change. This is also tested on production and it works fine there also. This change is already made on production environment.
This change will also need to be integrated into the DDMS source code such that the next time when a DDMS release will deployed it is not overwritten and works fine. So requesting to update the DDMS source code for this.

**Comment by rrowlands** [comment]
Thank you @Niteen12345 for the detailed explanation and thorough investigation. I have integrated your fix [into the source code.](https://github.com/terraframe/DDMS/commit/d52d400028ea3a62891aba0aa1fdada26fa1d695)
